export interface Application {
    applicationid:number
    dateYouPlanToLeaveUK:string
    dateYouPlanToArriveUK:string
    whatAreYouBeingPaidFor:string
    howMuchWillYouBePaid:number
    whoWillBePayingYouInUK:string
    passportExpiryDate:string
    passportIssueDate:string
    passportIssuingAuthority:string
    totalPrice:number
    lengthOfVisaVisit:number
    haveAddressInUK:number
    addressInUK:string
    familyInUK:number
    reasonWhyTherePayingForVisit:string
    howMuchMoneyAreTheyPaying:number
    relyOnYouFinancially:number
    receivedPublicFundsFromUK:number
    whoIsPayingYourVisit:string
    amountSpendEachMonth:number
    anotherIncome:number
    howMuchDoYouEarnAfterTax:number
}